// Code generated by dowse-gen; DO NOT EDIT.

package protocol

import "encoding/json"

// Ensure json import is used.
var _ = json.RawMessage{}

type CallHierarchyClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type CallHierarchyOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type CallHierarchyRegistrationOptions struct {
	DocumentSelector json.RawMessage `json:"documentSelector"`
	WorkDoneProgress *bool           `json:"workDoneProgress,omitempty"`
	Id               *string         `json:"id,omitempty"`
}

type ChangeAnnotationsSupportOptions struct {
	GroupsOnLabel *bool `json:"groupsOnLabel,omitempty"`
}

type ClientCapabilities struct {
	Workspace        *WorkspaceClientCapabilities        `json:"workspace,omitempty"`
	TextDocument     *TextDocumentClientCapabilities     `json:"textDocument,omitempty"`
	NotebookDocument *NotebookDocumentClientCapabilities `json:"notebookDocument,omitempty"`
	Window           *WindowClientCapabilities           `json:"window,omitempty"`
	General          *GeneralClientCapabilities          `json:"general,omitempty"`
	Experimental     json.RawMessage                     `json:"experimental,omitempty"`
}

type ClientCodeActionKindOptions struct {
	ValueSet []CodeActionKind `json:"valueSet"`
}

type ClientCodeActionLiteralOptions struct {
	CodeActionKind ClientCodeActionKindOptions `json:"codeActionKind"`
}

type ClientCodeActionResolveOptions struct {
	Properties []string `json:"properties"`
}

type ClientCodeLensResolveOptions struct {
	Properties []string `json:"properties"`
}

type ClientCompletionItemInsertTextModeOptions struct {
	ValueSet []InsertTextMode `json:"valueSet"`
}

type ClientCompletionItemOptions struct {
	SnippetSupport          *bool                                      `json:"snippetSupport,omitempty"`
	CommitCharactersSupport *bool                                      `json:"commitCharactersSupport,omitempty"`
	DocumentationFormat     []MarkupKind                               `json:"documentationFormat,omitempty"`
	DeprecatedSupport       *bool                                      `json:"deprecatedSupport,omitempty"`
	PreselectSupport        *bool                                      `json:"preselectSupport,omitempty"`
	TagSupport              *CompletionItemTagOptions                  `json:"tagSupport,omitempty"`
	InsertReplaceSupport    *bool                                      `json:"insertReplaceSupport,omitempty"`
	ResolveSupport          *ClientCompletionItemResolveOptions        `json:"resolveSupport,omitempty"`
	InsertTextModeSupport   *ClientCompletionItemInsertTextModeOptions `json:"insertTextModeSupport,omitempty"`
	LabelDetailsSupport     *bool                                      `json:"labelDetailsSupport,omitempty"`
}

type ClientCompletionItemOptionsKind struct {
	ValueSet []CompletionItemKind `json:"valueSet,omitempty"`
}

type ClientCompletionItemResolveOptions struct {
	Properties []string `json:"properties"`
}

type ClientDiagnosticsTagOptions struct {
	ValueSet []DiagnosticTag `json:"valueSet"`
}

type ClientFoldingRangeKindOptions struct {
	ValueSet []FoldingRangeKind `json:"valueSet,omitempty"`
}

type ClientFoldingRangeOptions struct {
	CollapsedText *bool `json:"collapsedText,omitempty"`
}

type ClientInfo struct {
	Name    string  `json:"name"`
	Version *string `json:"version,omitempty"`
}

type ClientInlayHintResolveOptions struct {
	Properties []string `json:"properties"`
}

type ClientSemanticTokensRequestFullDelta struct {
	Delta *bool `json:"delta,omitempty"`
}

type ClientSemanticTokensRequestOptions struct {
	Range json.RawMessage `json:"range,omitempty"`
	Full  json.RawMessage `json:"full,omitempty"`
}

type ClientShowMessageActionItemOptions struct {
	AdditionalPropertiesSupport *bool `json:"additionalPropertiesSupport,omitempty"`
}

type ClientSignatureInformationOptions struct {
	DocumentationFormat      []MarkupKind                                `json:"documentationFormat,omitempty"`
	ParameterInformation     *ClientSignatureParameterInformationOptions `json:"parameterInformation,omitempty"`
	ActiveParameterSupport   *bool                                       `json:"activeParameterSupport,omitempty"`
	NoActiveParameterSupport *bool                                       `json:"noActiveParameterSupport,omitempty"`
}

type ClientSignatureParameterInformationOptions struct {
	LabelOffsetSupport *bool `json:"labelOffsetSupport,omitempty"`
}

type ClientSymbolKindOptions struct {
	ValueSet []SymbolKind `json:"valueSet,omitempty"`
}

type ClientSymbolResolveOptions struct {
	Properties []string `json:"properties"`
}

type ClientSymbolTagOptions struct {
	ValueSet []SymbolTag `json:"valueSet"`
}

type CodeActionClientCapabilities struct {
	DynamicRegistration      *bool                           `json:"dynamicRegistration,omitempty"`
	CodeActionLiteralSupport *ClientCodeActionLiteralOptions `json:"codeActionLiteralSupport,omitempty"`
	IsPreferredSupport       *bool                           `json:"isPreferredSupport,omitempty"`
	DisabledSupport          *bool                           `json:"disabledSupport,omitempty"`
	DataSupport              *bool                           `json:"dataSupport,omitempty"`
	ResolveSupport           *ClientCodeActionResolveOptions `json:"resolveSupport,omitempty"`
	HonorsChangeAnnotations  *bool                           `json:"honorsChangeAnnotations,omitempty"`
	DocumentationSupport     *bool                           `json:"documentationSupport,omitempty"`
	TagSupport               *CodeActionTagOptions           `json:"tagSupport,omitempty"`
}

type CodeActionKind string

const (
	CodeActionKindEmpty                 CodeActionKind = ""
	CodeActionKindQuickFix              CodeActionKind = "quickfix"
	CodeActionKindRefactor              CodeActionKind = "refactor"
	CodeActionKindRefactorExtract       CodeActionKind = "refactor.extract"
	CodeActionKindRefactorInline        CodeActionKind = "refactor.inline"
	CodeActionKindRefactorMove          CodeActionKind = "refactor.move"
	CodeActionKindRefactorRewrite       CodeActionKind = "refactor.rewrite"
	CodeActionKindSource                CodeActionKind = "source"
	CodeActionKindSourceOrganizeImports CodeActionKind = "source.organizeImports"
	CodeActionKindSourceFixAll          CodeActionKind = "source.fixAll"
	CodeActionKindNotebook              CodeActionKind = "notebook"
)

type CodeActionKindDocumentation struct {
	Kind    CodeActionKind `json:"kind"`
	Command Command        `json:"command"`
}

type CodeActionOptions struct {
	WorkDoneProgress *bool                         `json:"workDoneProgress,omitempty"`
	CodeActionKinds  []CodeActionKind              `json:"codeActionKinds,omitempty"`
	Documentation    []CodeActionKindDocumentation `json:"documentation,omitempty"`
	ResolveProvider  *bool                         `json:"resolveProvider,omitempty"`
}

type CodeActionTag uint32

const (
	CodeActionTagLLMGenerated CodeActionTag = 1
)

type CodeActionTagOptions struct {
	ValueSet []CodeActionTag `json:"valueSet"`
}

type CodeDescription struct {
	Href string `json:"href"`
}

type CodeLensClientCapabilities struct {
	DynamicRegistration *bool                         `json:"dynamicRegistration,omitempty"`
	ResolveSupport      *ClientCodeLensResolveOptions `json:"resolveSupport,omitempty"`
}

type CodeLensOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
	ResolveProvider  *bool `json:"resolveProvider,omitempty"`
}

type CodeLensWorkspaceClientCapabilities struct {
	RefreshSupport *bool `json:"refreshSupport,omitempty"`
}

type Command struct {
	Title     string            `json:"title"`
	Tooltip   *string           `json:"tooltip,omitempty"`
	Command   string            `json:"command"`
	Arguments []json.RawMessage `json:"arguments,omitempty"`
}

type CompletionClientCapabilities struct {
	DynamicRegistration *bool                            `json:"dynamicRegistration,omitempty"`
	CompletionItem      *ClientCompletionItemOptions     `json:"completionItem,omitempty"`
	CompletionItemKind  *ClientCompletionItemOptionsKind `json:"completionItemKind,omitempty"`
	InsertTextMode      *InsertTextMode                  `json:"insertTextMode,omitempty"`
	ContextSupport      *bool                            `json:"contextSupport,omitempty"`
	CompletionList      *CompletionListCapabilities      `json:"completionList,omitempty"`
}

type CompletionItemKind uint32

const (
	CompletionItemKindText          CompletionItemKind = 1
	CompletionItemKindMethod        CompletionItemKind = 2
	CompletionItemKindFunction      CompletionItemKind = 3
	CompletionItemKindConstructor   CompletionItemKind = 4
	CompletionItemKindField         CompletionItemKind = 5
	CompletionItemKindVariable      CompletionItemKind = 6
	CompletionItemKindClass         CompletionItemKind = 7
	CompletionItemKindInterface     CompletionItemKind = 8
	CompletionItemKindModule        CompletionItemKind = 9
	CompletionItemKindProperty      CompletionItemKind = 10
	CompletionItemKindUnit          CompletionItemKind = 11
	CompletionItemKindValue         CompletionItemKind = 12
	CompletionItemKindEnum          CompletionItemKind = 13
	CompletionItemKindKeyword       CompletionItemKind = 14
	CompletionItemKindSnippet       CompletionItemKind = 15
	CompletionItemKindColor         CompletionItemKind = 16
	CompletionItemKindFile          CompletionItemKind = 17
	CompletionItemKindReference     CompletionItemKind = 18
	CompletionItemKindFolder        CompletionItemKind = 19
	CompletionItemKindEnumMember    CompletionItemKind = 20
	CompletionItemKindConstant      CompletionItemKind = 21
	CompletionItemKindStruct        CompletionItemKind = 22
	CompletionItemKindEvent         CompletionItemKind = 23
	CompletionItemKindOperator      CompletionItemKind = 24
	CompletionItemKindTypeParameter CompletionItemKind = 25
)

type CompletionItemTag uint32

const (
	CompletionItemTagDeprecated CompletionItemTag = 1
)

type CompletionItemTagOptions struct {
	ValueSet []CompletionItemTag `json:"valueSet"`
}

type CompletionListCapabilities struct {
	ItemDefaults     []string `json:"itemDefaults,omitempty"`
	ApplyKindSupport *bool    `json:"applyKindSupport,omitempty"`
}

type CompletionOptions struct {
	WorkDoneProgress    *bool                        `json:"workDoneProgress,omitempty"`
	TriggerCharacters   []string                     `json:"triggerCharacters,omitempty"`
	AllCommitCharacters []string                     `json:"allCommitCharacters,omitempty"`
	ResolveProvider     *bool                        `json:"resolveProvider,omitempty"`
	CompletionItem      *ServerCompletionItemOptions `json:"completionItem,omitempty"`
}

type DeclarationClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	LinkSupport         *bool `json:"linkSupport,omitempty"`
}

type DeclarationOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type DeclarationRegistrationOptions struct {
	WorkDoneProgress *bool           `json:"workDoneProgress,omitempty"`
	DocumentSelector json.RawMessage `json:"documentSelector"`
	Id               *string         `json:"id,omitempty"`
}

type DefinitionClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	LinkSupport         *bool `json:"linkSupport,omitempty"`
}

type DefinitionOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type DefinitionParams struct {
	TextDocument       TextDocumentIdentifier `json:"textDocument"`
	Position           Position               `json:"position"`
	WorkDoneToken      json.RawMessage        `json:"workDoneToken,omitempty"`
	PartialResultToken json.RawMessage        `json:"partialResultToken,omitempty"`
}

type Diagnostic struct {
	Range              Range                          `json:"range"`
	Severity           *DiagnosticSeverity            `json:"severity,omitempty"`
	Code               json.RawMessage                `json:"code,omitempty"`
	CodeDescription    *CodeDescription               `json:"codeDescription,omitempty"`
	Source             *string                        `json:"source,omitempty"`
	Message            string                         `json:"message"`
	Tags               []DiagnosticTag                `json:"tags,omitempty"`
	RelatedInformation []DiagnosticRelatedInformation `json:"relatedInformation,omitempty"`
	Data               json.RawMessage                `json:"data,omitempty"`
}

type DiagnosticClientCapabilities struct {
	RelatedInformation     *bool                        `json:"relatedInformation,omitempty"`
	TagSupport             *ClientDiagnosticsTagOptions `json:"tagSupport,omitempty"`
	CodeDescriptionSupport *bool                        `json:"codeDescriptionSupport,omitempty"`
	DataSupport            *bool                        `json:"dataSupport,omitempty"`
	DynamicRegistration    *bool                        `json:"dynamicRegistration,omitempty"`
	RelatedDocumentSupport *bool                        `json:"relatedDocumentSupport,omitempty"`
}

type DiagnosticOptions struct {
	WorkDoneProgress      *bool   `json:"workDoneProgress,omitempty"`
	Identifier            *string `json:"identifier,omitempty"`
	InterFileDependencies bool    `json:"interFileDependencies"`
	WorkspaceDiagnostics  bool    `json:"workspaceDiagnostics"`
}

type DiagnosticRegistrationOptions struct {
	DocumentSelector      json.RawMessage `json:"documentSelector"`
	WorkDoneProgress      *bool           `json:"workDoneProgress,omitempty"`
	Identifier            *string         `json:"identifier,omitempty"`
	InterFileDependencies bool            `json:"interFileDependencies"`
	WorkspaceDiagnostics  bool            `json:"workspaceDiagnostics"`
	Id                    *string         `json:"id,omitempty"`
}

type DiagnosticRelatedInformation struct {
	Location Location `json:"location"`
	Message  string   `json:"message"`
}

type DiagnosticSeverity uint32

const (
	DiagnosticSeverityError       DiagnosticSeverity = 1
	DiagnosticSeverityWarning     DiagnosticSeverity = 2
	DiagnosticSeverityInformation DiagnosticSeverity = 3
	DiagnosticSeverityHint        DiagnosticSeverity = 4
)

type DiagnosticTag uint32

const (
	DiagnosticTagUnnecessary DiagnosticTag = 1
	DiagnosticTagDeprecated  DiagnosticTag = 2
)

type DiagnosticWorkspaceClientCapabilities struct {
	RefreshSupport *bool `json:"refreshSupport,omitempty"`
}

type DiagnosticsCapabilities struct {
	RelatedInformation     *bool                        `json:"relatedInformation,omitempty"`
	TagSupport             *ClientDiagnosticsTagOptions `json:"tagSupport,omitempty"`
	CodeDescriptionSupport *bool                        `json:"codeDescriptionSupport,omitempty"`
	DataSupport            *bool                        `json:"dataSupport,omitempty"`
}

type DidChangeConfigurationClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type DidChangeTextDocumentParams struct {
	TextDocument   VersionedTextDocumentIdentifier  `json:"textDocument"`
	ContentChanges []TextDocumentContentChangeEvent `json:"contentChanges"`
}

type DidChangeWatchedFilesClientCapabilities struct {
	DynamicRegistration    *bool `json:"dynamicRegistration,omitempty"`
	RelativePatternSupport *bool `json:"relativePatternSupport,omitempty"`
}

type DidCloseTextDocumentParams struct {
	TextDocument TextDocumentIdentifier `json:"textDocument"`
}

type DidOpenTextDocumentParams struct {
	TextDocument TextDocumentItem `json:"textDocument"`
}

type DocumentColorClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type DocumentColorOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type DocumentColorRegistrationOptions struct {
	DocumentSelector json.RawMessage `json:"documentSelector"`
	WorkDoneProgress *bool           `json:"workDoneProgress,omitempty"`
	Id               *string         `json:"id,omitempty"`
}

type DocumentDiagnosticParams struct {
	WorkDoneToken      json.RawMessage        `json:"workDoneToken,omitempty"`
	PartialResultToken json.RawMessage        `json:"partialResultToken,omitempty"`
	TextDocument       TextDocumentIdentifier `json:"textDocument"`
	Identifier         *string                `json:"identifier,omitempty"`
	PreviousResultId   *string                `json:"previousResultId,omitempty"`
}

type DocumentFormattingClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type DocumentFormattingOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type DocumentHighlightClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type DocumentHighlightOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type DocumentLinkClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	TooltipSupport      *bool `json:"tooltipSupport,omitempty"`
}

type DocumentLinkOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
	ResolveProvider  *bool `json:"resolveProvider,omitempty"`
}

type DocumentOnTypeFormattingClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type DocumentOnTypeFormattingOptions struct {
	FirstTriggerCharacter string   `json:"firstTriggerCharacter"`
	MoreTriggerCharacter  []string `json:"moreTriggerCharacter,omitempty"`
}

type DocumentRangeFormattingClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	RangesSupport       *bool `json:"rangesSupport,omitempty"`
}

type DocumentRangeFormattingOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
	RangesSupport    *bool `json:"rangesSupport,omitempty"`
}

type DocumentSymbolClientCapabilities struct {
	DynamicRegistration               *bool                    `json:"dynamicRegistration,omitempty"`
	SymbolKind                        *ClientSymbolKindOptions `json:"symbolKind,omitempty"`
	HierarchicalDocumentSymbolSupport *bool                    `json:"hierarchicalDocumentSymbolSupport,omitempty"`
	TagSupport                        *ClientSymbolTagOptions  `json:"tagSupport,omitempty"`
	LabelSupport                      *bool                    `json:"labelSupport,omitempty"`
}

type DocumentSymbolOptions struct {
	WorkDoneProgress *bool   `json:"workDoneProgress,omitempty"`
	Label            *string `json:"label,omitempty"`
}

type ExecuteCommandClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type ExecuteCommandOptions struct {
	WorkDoneProgress *bool    `json:"workDoneProgress,omitempty"`
	Commands         []string `json:"commands"`
}

type FailureHandlingKind string

const (
	FailureHandlingKindAbort                 FailureHandlingKind = "abort"
	FailureHandlingKindTransactional         FailureHandlingKind = "transactional"
	FailureHandlingKindTextOnlyTransactional FailureHandlingKind = "textOnlyTransactional"
	FailureHandlingKindUndo                  FailureHandlingKind = "undo"
)

type FileOperationClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	DidCreate           *bool `json:"didCreate,omitempty"`
	WillCreate          *bool `json:"willCreate,omitempty"`
	DidRename           *bool `json:"didRename,omitempty"`
	WillRename          *bool `json:"willRename,omitempty"`
	DidDelete           *bool `json:"didDelete,omitempty"`
	WillDelete          *bool `json:"willDelete,omitempty"`
}

type FileOperationFilter struct {
	Scheme  *string              `json:"scheme,omitempty"`
	Pattern FileOperationPattern `json:"pattern"`
}

type FileOperationOptions struct {
	DidCreate  *FileOperationRegistrationOptions `json:"didCreate,omitempty"`
	WillCreate *FileOperationRegistrationOptions `json:"willCreate,omitempty"`
	DidRename  *FileOperationRegistrationOptions `json:"didRename,omitempty"`
	WillRename *FileOperationRegistrationOptions `json:"willRename,omitempty"`
	DidDelete  *FileOperationRegistrationOptions `json:"didDelete,omitempty"`
	WillDelete *FileOperationRegistrationOptions `json:"willDelete,omitempty"`
}

type FileOperationPattern struct {
	Glob    string                       `json:"glob"`
	Matches *FileOperationPatternKind    `json:"matches,omitempty"`
	Options *FileOperationPatternOptions `json:"options,omitempty"`
}

type FileOperationPatternKind string

const (
	FileOperationPatternKindFile   FileOperationPatternKind = "file"
	FileOperationPatternKindFolder FileOperationPatternKind = "folder"
)

type FileOperationPatternOptions struct {
	IgnoreCase *bool `json:"ignoreCase,omitempty"`
}

type FileOperationRegistrationOptions struct {
	Filters []FileOperationFilter `json:"filters"`
}

type FoldingRangeClientCapabilities struct {
	DynamicRegistration *bool                          `json:"dynamicRegistration,omitempty"`
	RangeLimit          *uint32                        `json:"rangeLimit,omitempty"`
	LineFoldingOnly     *bool                          `json:"lineFoldingOnly,omitempty"`
	FoldingRangeKind    *ClientFoldingRangeKindOptions `json:"foldingRangeKind,omitempty"`
	FoldingRange        *ClientFoldingRangeOptions     `json:"foldingRange,omitempty"`
}

type FoldingRangeKind string

const (
	FoldingRangeKindComment FoldingRangeKind = "comment"
	FoldingRangeKindImports FoldingRangeKind = "imports"
	FoldingRangeKindRegion  FoldingRangeKind = "region"
)

type FoldingRangeOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type FoldingRangeRegistrationOptions struct {
	DocumentSelector json.RawMessage `json:"documentSelector"`
	WorkDoneProgress *bool           `json:"workDoneProgress,omitempty"`
	Id               *string         `json:"id,omitempty"`
}

type FoldingRangeWorkspaceClientCapabilities struct {
	RefreshSupport *bool `json:"refreshSupport,omitempty"`
}

type FullDocumentDiagnosticReport struct {
	Kind     string       `json:"kind"`
	ResultId *string      `json:"resultId,omitempty"`
	Items    []Diagnostic `json:"items"`
}

type GeneralClientCapabilities struct {
	StaleRequestSupport *StaleRequestSupportOptions           `json:"staleRequestSupport,omitempty"`
	RegularExpressions  *RegularExpressionsClientCapabilities `json:"regularExpressions,omitempty"`
	Markdown            *MarkdownClientCapabilities           `json:"markdown,omitempty"`
	PositionEncodings   []PositionEncodingKind                `json:"positionEncodings,omitempty"`
}

type GlobPattern = json.RawMessage

type HoverClientCapabilities struct {
	DynamicRegistration *bool        `json:"dynamicRegistration,omitempty"`
	ContentFormat       []MarkupKind `json:"contentFormat,omitempty"`
}

type HoverOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type ImplementationClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	LinkSupport         *bool `json:"linkSupport,omitempty"`
}

type ImplementationOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type ImplementationRegistrationOptions struct {
	DocumentSelector json.RawMessage `json:"documentSelector"`
	WorkDoneProgress *bool           `json:"workDoneProgress,omitempty"`
	Id               *string         `json:"id,omitempty"`
}

type InitializeParams struct {
	WorkDoneToken         json.RawMessage    `json:"workDoneToken,omitempty"`
	ProcessId             int32              `json:"processId"`
	ClientInfo            *ClientInfo        `json:"clientInfo,omitempty"`
	Locale                *string            `json:"locale,omitempty"`
	RootPath              *string            `json:"rootPath,omitempty"`
	RootUri               string             `json:"rootUri"`
	Capabilities          ClientCapabilities `json:"capabilities"`
	InitializationOptions json.RawMessage    `json:"initializationOptions,omitempty"`
	Trace                 *TraceValue        `json:"trace,omitempty"`
	WorkspaceFolders      []WorkspaceFolder  `json:"workspaceFolders,omitempty"`
}

type InitializeResult struct {
	Capabilities ServerCapabilities `json:"capabilities"`
	ServerInfo   *ServerInfo        `json:"serverInfo,omitempty"`
}

type InlayHintClientCapabilities struct {
	DynamicRegistration *bool                          `json:"dynamicRegistration,omitempty"`
	ResolveSupport      *ClientInlayHintResolveOptions `json:"resolveSupport,omitempty"`
}

type InlayHintOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
	ResolveProvider  *bool `json:"resolveProvider,omitempty"`
}

type InlayHintRegistrationOptions struct {
	WorkDoneProgress *bool           `json:"workDoneProgress,omitempty"`
	ResolveProvider  *bool           `json:"resolveProvider,omitempty"`
	DocumentSelector json.RawMessage `json:"documentSelector"`
	Id               *string         `json:"id,omitempty"`
}

type InlayHintWorkspaceClientCapabilities struct {
	RefreshSupport *bool `json:"refreshSupport,omitempty"`
}

type InlineCompletionClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type InlineCompletionOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type InlineValueClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type InlineValueOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type InlineValueRegistrationOptions struct {
	WorkDoneProgress *bool           `json:"workDoneProgress,omitempty"`
	DocumentSelector json.RawMessage `json:"documentSelector"`
	Id               *string         `json:"id,omitempty"`
}

type InlineValueWorkspaceClientCapabilities struct {
	RefreshSupport *bool `json:"refreshSupport,omitempty"`
}

type InsertTextMode uint32

const (
	InsertTextModeAsIs              InsertTextMode = 1
	InsertTextModeAdjustIndentation InsertTextMode = 2
)

type LanguageKind string

const (
	LanguageKindABAP            LanguageKind = "abap"
	LanguageKindWindowsBat      LanguageKind = "bat"
	LanguageKindBibTeX          LanguageKind = "bibtex"
	LanguageKindClojure         LanguageKind = "clojure"
	LanguageKindCoffeescript    LanguageKind = "coffeescript"
	LanguageKindC               LanguageKind = "c"
	LanguageKindCPP             LanguageKind = "cpp"
	LanguageKindCSharp          LanguageKind = "csharp"
	LanguageKindCSS             LanguageKind = "css"
	LanguageKindD               LanguageKind = "d"
	LanguageKindDelphi          LanguageKind = "pascal"
	LanguageKindDiff            LanguageKind = "diff"
	LanguageKindDart            LanguageKind = "dart"
	LanguageKindDockerfile      LanguageKind = "dockerfile"
	LanguageKindElixir          LanguageKind = "elixir"
	LanguageKindErlang          LanguageKind = "erlang"
	LanguageKindFSharp          LanguageKind = "fsharp"
	LanguageKindGitCommit       LanguageKind = "git-commit"
	LanguageKindGitRebase       LanguageKind = "rebase"
	LanguageKindGo              LanguageKind = "go"
	LanguageKindGroovy          LanguageKind = "groovy"
	LanguageKindHandlebars      LanguageKind = "handlebars"
	LanguageKindHaskell         LanguageKind = "haskell"
	LanguageKindHTML            LanguageKind = "html"
	LanguageKindIni             LanguageKind = "ini"
	LanguageKindJava            LanguageKind = "java"
	LanguageKindJavaScript      LanguageKind = "javascript"
	LanguageKindJavaScriptReact LanguageKind = "javascriptreact"
	LanguageKindJSON            LanguageKind = "json"
	LanguageKindLaTeX           LanguageKind = "latex"
	LanguageKindLess            LanguageKind = "less"
	LanguageKindLua             LanguageKind = "lua"
	LanguageKindMakefile        LanguageKind = "makefile"
	LanguageKindMarkdown        LanguageKind = "markdown"
	LanguageKindObjectiveC      LanguageKind = "objective-c"
	LanguageKindObjectiveCPP    LanguageKind = "objective-cpp"
	LanguageKindPascal          LanguageKind = "pascal"
	LanguageKindPerl            LanguageKind = "perl"
	LanguageKindPerl6           LanguageKind = "perl6"
	LanguageKindPHP             LanguageKind = "php"
	LanguageKindPowershell      LanguageKind = "powershell"
	LanguageKindPug             LanguageKind = "jade"
	LanguageKindPython          LanguageKind = "python"
	LanguageKindR               LanguageKind = "r"
	LanguageKindRazor           LanguageKind = "razor"
	LanguageKindRuby            LanguageKind = "ruby"
	LanguageKindRust            LanguageKind = "rust"
	LanguageKindSCSS            LanguageKind = "scss"
	LanguageKindSASS            LanguageKind = "sass"
	LanguageKindScala           LanguageKind = "scala"
	LanguageKindShaderLab       LanguageKind = "shaderlab"
	LanguageKindShellScript     LanguageKind = "shellscript"
	LanguageKindSQL             LanguageKind = "sql"
	LanguageKindSwift           LanguageKind = "swift"
	LanguageKindTypeScript      LanguageKind = "typescript"
	LanguageKindTypeScriptReact LanguageKind = "typescriptreact"
	LanguageKindTeX             LanguageKind = "tex"
	LanguageKindVisualBasic     LanguageKind = "vb"
	LanguageKindXML             LanguageKind = "xml"
	LanguageKindXSL             LanguageKind = "xsl"
	LanguageKindYAML            LanguageKind = "yaml"
)

type LinkedEditingRangeClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type LinkedEditingRangeOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type LinkedEditingRangeRegistrationOptions struct {
	DocumentSelector json.RawMessage `json:"documentSelector"`
	WorkDoneProgress *bool           `json:"workDoneProgress,omitempty"`
	Id               *string         `json:"id,omitempty"`
}

type Location struct {
	Uri   string `json:"uri"`
	Range Range  `json:"range"`
}

type MarkdownClientCapabilities struct {
	Parser      string   `json:"parser"`
	Version     *string  `json:"version,omitempty"`
	AllowedTags []string `json:"allowedTags,omitempty"`
}

type MarkupKind string

const (
	MarkupKindPlainText MarkupKind = "plaintext"
	MarkupKindMarkdown  MarkupKind = "markdown"
)

type MonikerClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type MonikerOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type MonikerRegistrationOptions struct {
	DocumentSelector json.RawMessage `json:"documentSelector"`
	WorkDoneProgress *bool           `json:"workDoneProgress,omitempty"`
}

type NotebookCellLanguage struct {
	Language string `json:"language"`
}

type NotebookDocumentClientCapabilities struct {
	Synchronization NotebookDocumentSyncClientCapabilities `json:"synchronization"`
}

type NotebookDocumentFilter = json.RawMessage

type NotebookDocumentFilterNotebookType struct {
	NotebookType string       `json:"notebookType"`
	Scheme       *string      `json:"scheme,omitempty"`
	Pattern      *GlobPattern `json:"pattern,omitempty"`
}

type NotebookDocumentFilterPattern struct {
	NotebookType *string     `json:"notebookType,omitempty"`
	Scheme       *string     `json:"scheme,omitempty"`
	Pattern      GlobPattern `json:"pattern"`
}

type NotebookDocumentFilterScheme struct {
	NotebookType *string      `json:"notebookType,omitempty"`
	Scheme       string       `json:"scheme"`
	Pattern      *GlobPattern `json:"pattern,omitempty"`
}

type NotebookDocumentFilterWithCells struct {
	Notebook json.RawMessage        `json:"notebook,omitempty"`
	Cells    []NotebookCellLanguage `json:"cells"`
}

type NotebookDocumentFilterWithNotebook struct {
	Notebook json.RawMessage        `json:"notebook"`
	Cells    []NotebookCellLanguage `json:"cells,omitempty"`
}

type NotebookDocumentSyncClientCapabilities struct {
	DynamicRegistration     *bool `json:"dynamicRegistration,omitempty"`
	ExecutionSummarySupport *bool `json:"executionSummarySupport,omitempty"`
}

type NotebookDocumentSyncOptions struct {
	NotebookSelector []json.RawMessage `json:"notebookSelector"`
	Save             *bool             `json:"save,omitempty"`
}

type NotebookDocumentSyncRegistrationOptions struct {
	NotebookSelector []json.RawMessage `json:"notebookSelector"`
	Save             *bool             `json:"save,omitempty"`
	Id               *string           `json:"id,omitempty"`
}

type PartialResultParams struct {
	PartialResultToken json.RawMessage `json:"partialResultToken,omitempty"`
}

type Pattern = string

type Position struct {
	Line      uint32 `json:"line"`
	Character uint32 `json:"character"`
}

type PositionEncodingKind string

const (
	PositionEncodingKindUTF8  PositionEncodingKind = "utf-8"
	PositionEncodingKindUTF16 PositionEncodingKind = "utf-16"
	PositionEncodingKindUTF32 PositionEncodingKind = "utf-32"
)

type PrepareSupportDefaultBehavior uint32

const (
	PrepareSupportDefaultBehaviorIdentifier PrepareSupportDefaultBehavior = 1
)

type ProgressParams struct {
	Token json.RawMessage `json:"token"`
	Value json.RawMessage `json:"value"`
}

type PublishDiagnosticsClientCapabilities struct {
	RelatedInformation     *bool                        `json:"relatedInformation,omitempty"`
	TagSupport             *ClientDiagnosticsTagOptions `json:"tagSupport,omitempty"`
	CodeDescriptionSupport *bool                        `json:"codeDescriptionSupport,omitempty"`
	DataSupport            *bool                        `json:"dataSupport,omitempty"`
	VersionSupport         *bool                        `json:"versionSupport,omitempty"`
}

type PublishDiagnosticsParams struct {
	Uri         string       `json:"uri"`
	Version     *int32       `json:"version,omitempty"`
	Diagnostics []Diagnostic `json:"diagnostics"`
}

type Range struct {
	Start Position `json:"start"`
	End   Position `json:"end"`
}

type ReferenceClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type ReferenceOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type RegularExpressionEngineKind = string

type RegularExpressionsClientCapabilities struct {
	Engine  RegularExpressionEngineKind `json:"engine"`
	Version *string                     `json:"version,omitempty"`
}

type RelatedFullDocumentDiagnosticReport struct {
	Kind             string                     `json:"kind"`
	ResultId         *string                    `json:"resultId,omitempty"`
	Items            []Diagnostic               `json:"items"`
	RelatedDocuments map[string]json.RawMessage `json:"relatedDocuments,omitempty"`
}

type RelativePattern struct {
	BaseUri json.RawMessage `json:"baseUri"`
	Pattern Pattern         `json:"pattern"`
}

type RenameClientCapabilities struct {
	DynamicRegistration           *bool                          `json:"dynamicRegistration,omitempty"`
	PrepareSupport                *bool                          `json:"prepareSupport,omitempty"`
	PrepareSupportDefaultBehavior *PrepareSupportDefaultBehavior `json:"prepareSupportDefaultBehavior,omitempty"`
	HonorsChangeAnnotations       *bool                          `json:"honorsChangeAnnotations,omitempty"`
}

type RenameOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
	PrepareProvider  *bool `json:"prepareProvider,omitempty"`
}

type ResourceOperationKind string

const (
	ResourceOperationKindCreate ResourceOperationKind = "create"
	ResourceOperationKindRename ResourceOperationKind = "rename"
	ResourceOperationKindDelete ResourceOperationKind = "delete"
)

type SaveOptions struct {
	IncludeText *bool `json:"includeText,omitempty"`
}

type SelectionRangeClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type SelectionRangeOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type SelectionRangeRegistrationOptions struct {
	WorkDoneProgress *bool           `json:"workDoneProgress,omitempty"`
	DocumentSelector json.RawMessage `json:"documentSelector"`
	Id               *string         `json:"id,omitempty"`
}

type SemanticTokensClientCapabilities struct {
	DynamicRegistration     *bool                              `json:"dynamicRegistration,omitempty"`
	Requests                ClientSemanticTokensRequestOptions `json:"requests"`
	TokenTypes              []string                           `json:"tokenTypes"`
	TokenModifiers          []string                           `json:"tokenModifiers"`
	Formats                 []TokenFormat                      `json:"formats"`
	OverlappingTokenSupport *bool                              `json:"overlappingTokenSupport,omitempty"`
	MultilineTokenSupport   *bool                              `json:"multilineTokenSupport,omitempty"`
	ServerCancelSupport     *bool                              `json:"serverCancelSupport,omitempty"`
	AugmentsSyntaxTokens    *bool                              `json:"augmentsSyntaxTokens,omitempty"`
}

type SemanticTokensFullDelta struct {
	Delta *bool `json:"delta,omitempty"`
}

type SemanticTokensLegend struct {
	TokenTypes     []string `json:"tokenTypes"`
	TokenModifiers []string `json:"tokenModifiers"`
}

type SemanticTokensOptions struct {
	WorkDoneProgress *bool                `json:"workDoneProgress,omitempty"`
	Legend           SemanticTokensLegend `json:"legend"`
	Range            json.RawMessage      `json:"range,omitempty"`
	Full             json.RawMessage      `json:"full,omitempty"`
}

type SemanticTokensRegistrationOptions struct {
	DocumentSelector json.RawMessage      `json:"documentSelector"`
	WorkDoneProgress *bool                `json:"workDoneProgress,omitempty"`
	Legend           SemanticTokensLegend `json:"legend"`
	Range            json.RawMessage      `json:"range,omitempty"`
	Full             json.RawMessage      `json:"full,omitempty"`
	Id               *string              `json:"id,omitempty"`
}

type SemanticTokensWorkspaceClientCapabilities struct {
	RefreshSupport *bool `json:"refreshSupport,omitempty"`
}

type ServerCapabilities struct {
	PositionEncoding                 *PositionEncodingKind            `json:"positionEncoding,omitempty"`
	TextDocumentSync                 json.RawMessage                  `json:"textDocumentSync,omitempty"`
	NotebookDocumentSync             json.RawMessage                  `json:"notebookDocumentSync,omitempty"`
	CompletionProvider               *CompletionOptions               `json:"completionProvider,omitempty"`
	HoverProvider                    json.RawMessage                  `json:"hoverProvider,omitempty"`
	SignatureHelpProvider            *SignatureHelpOptions            `json:"signatureHelpProvider,omitempty"`
	DeclarationProvider              json.RawMessage                  `json:"declarationProvider,omitempty"`
	DefinitionProvider               json.RawMessage                  `json:"definitionProvider,omitempty"`
	TypeDefinitionProvider           json.RawMessage                  `json:"typeDefinitionProvider,omitempty"`
	ImplementationProvider           json.RawMessage                  `json:"implementationProvider,omitempty"`
	ReferencesProvider               json.RawMessage                  `json:"referencesProvider,omitempty"`
	DocumentHighlightProvider        json.RawMessage                  `json:"documentHighlightProvider,omitempty"`
	DocumentSymbolProvider           json.RawMessage                  `json:"documentSymbolProvider,omitempty"`
	CodeActionProvider               json.RawMessage                  `json:"codeActionProvider,omitempty"`
	CodeLensProvider                 *CodeLensOptions                 `json:"codeLensProvider,omitempty"`
	DocumentLinkProvider             *DocumentLinkOptions             `json:"documentLinkProvider,omitempty"`
	ColorProvider                    json.RawMessage                  `json:"colorProvider,omitempty"`
	WorkspaceSymbolProvider          json.RawMessage                  `json:"workspaceSymbolProvider,omitempty"`
	DocumentFormattingProvider       json.RawMessage                  `json:"documentFormattingProvider,omitempty"`
	DocumentRangeFormattingProvider  json.RawMessage                  `json:"documentRangeFormattingProvider,omitempty"`
	DocumentOnTypeFormattingProvider *DocumentOnTypeFormattingOptions `json:"documentOnTypeFormattingProvider,omitempty"`
	RenameProvider                   json.RawMessage                  `json:"renameProvider,omitempty"`
	FoldingRangeProvider             json.RawMessage                  `json:"foldingRangeProvider,omitempty"`
	SelectionRangeProvider           json.RawMessage                  `json:"selectionRangeProvider,omitempty"`
	ExecuteCommandProvider           *ExecuteCommandOptions           `json:"executeCommandProvider,omitempty"`
	CallHierarchyProvider            json.RawMessage                  `json:"callHierarchyProvider,omitempty"`
	LinkedEditingRangeProvider       json.RawMessage                  `json:"linkedEditingRangeProvider,omitempty"`
	SemanticTokensProvider           json.RawMessage                  `json:"semanticTokensProvider,omitempty"`
	MonikerProvider                  json.RawMessage                  `json:"monikerProvider,omitempty"`
	TypeHierarchyProvider            json.RawMessage                  `json:"typeHierarchyProvider,omitempty"`
	InlineValueProvider              json.RawMessage                  `json:"inlineValueProvider,omitempty"`
	InlayHintProvider                json.RawMessage                  `json:"inlayHintProvider,omitempty"`
	DiagnosticProvider               json.RawMessage                  `json:"diagnosticProvider,omitempty"`
	InlineCompletionProvider         json.RawMessage                  `json:"inlineCompletionProvider,omitempty"`
	Workspace                        *WorkspaceOptions                `json:"workspace,omitempty"`
	Experimental                     json.RawMessage                  `json:"experimental,omitempty"`
}

type ServerCompletionItemOptions struct {
	LabelDetailsSupport *bool `json:"labelDetailsSupport,omitempty"`
}

type ServerInfo struct {
	Name    string  `json:"name"`
	Version *string `json:"version,omitempty"`
}

type ShowDocumentClientCapabilities struct {
	Support bool `json:"support"`
}

type ShowMessageRequestClientCapabilities struct {
	MessageActionItem *ClientShowMessageActionItemOptions `json:"messageActionItem,omitempty"`
}

type SignatureHelpClientCapabilities struct {
	DynamicRegistration  *bool                              `json:"dynamicRegistration,omitempty"`
	SignatureInformation *ClientSignatureInformationOptions `json:"signatureInformation,omitempty"`
	ContextSupport       *bool                              `json:"contextSupport,omitempty"`
}

type SignatureHelpOptions struct {
	WorkDoneProgress    *bool    `json:"workDoneProgress,omitempty"`
	TriggerCharacters   []string `json:"triggerCharacters,omitempty"`
	RetriggerCharacters []string `json:"retriggerCharacters,omitempty"`
}

type StaleRequestSupportOptions struct {
	Cancel                 bool     `json:"cancel"`
	RetryOnContentModified []string `json:"retryOnContentModified"`
}

type StaticRegistrationOptions struct {
	Id *string `json:"id,omitempty"`
}

type SymbolKind uint32

const (
	SymbolKindFile          SymbolKind = 1
	SymbolKindModule        SymbolKind = 2
	SymbolKindNamespace     SymbolKind = 3
	SymbolKindPackage       SymbolKind = 4
	SymbolKindClass         SymbolKind = 5
	SymbolKindMethod        SymbolKind = 6
	SymbolKindProperty      SymbolKind = 7
	SymbolKindField         SymbolKind = 8
	SymbolKindConstructor   SymbolKind = 9
	SymbolKindEnum          SymbolKind = 10
	SymbolKindInterface     SymbolKind = 11
	SymbolKindFunction      SymbolKind = 12
	SymbolKindVariable      SymbolKind = 13
	SymbolKindConstant      SymbolKind = 14
	SymbolKindString        SymbolKind = 15
	SymbolKindNumber        SymbolKind = 16
	SymbolKindBoolean       SymbolKind = 17
	SymbolKindArray         SymbolKind = 18
	SymbolKindObject        SymbolKind = 19
	SymbolKindKey           SymbolKind = 20
	SymbolKindNull          SymbolKind = 21
	SymbolKindEnumMember    SymbolKind = 22
	SymbolKindStruct        SymbolKind = 23
	SymbolKindEvent         SymbolKind = 24
	SymbolKindOperator      SymbolKind = 25
	SymbolKindTypeParameter SymbolKind = 26
)

type SymbolTag uint32

const (
	SymbolTagDeprecated SymbolTag = 1
)

type TextDocumentClientCapabilities struct {
	Synchronization    *TextDocumentSyncClientCapabilities         `json:"synchronization,omitempty"`
	Filters            *TextDocumentFilterClientCapabilities       `json:"filters,omitempty"`
	Completion         *CompletionClientCapabilities               `json:"completion,omitempty"`
	Hover              *HoverClientCapabilities                    `json:"hover,omitempty"`
	SignatureHelp      *SignatureHelpClientCapabilities            `json:"signatureHelp,omitempty"`
	Declaration        *DeclarationClientCapabilities              `json:"declaration,omitempty"`
	Definition         *DefinitionClientCapabilities               `json:"definition,omitempty"`
	TypeDefinition     *TypeDefinitionClientCapabilities           `json:"typeDefinition,omitempty"`
	Implementation     *ImplementationClientCapabilities           `json:"implementation,omitempty"`
	References         *ReferenceClientCapabilities                `json:"references,omitempty"`
	DocumentHighlight  *DocumentHighlightClientCapabilities        `json:"documentHighlight,omitempty"`
	DocumentSymbol     *DocumentSymbolClientCapabilities           `json:"documentSymbol,omitempty"`
	CodeAction         *CodeActionClientCapabilities               `json:"codeAction,omitempty"`
	CodeLens           *CodeLensClientCapabilities                 `json:"codeLens,omitempty"`
	DocumentLink       *DocumentLinkClientCapabilities             `json:"documentLink,omitempty"`
	ColorProvider      *DocumentColorClientCapabilities            `json:"colorProvider,omitempty"`
	Formatting         *DocumentFormattingClientCapabilities       `json:"formatting,omitempty"`
	RangeFormatting    *DocumentRangeFormattingClientCapabilities  `json:"rangeFormatting,omitempty"`
	OnTypeFormatting   *DocumentOnTypeFormattingClientCapabilities `json:"onTypeFormatting,omitempty"`
	Rename             *RenameClientCapabilities                   `json:"rename,omitempty"`
	FoldingRange       *FoldingRangeClientCapabilities             `json:"foldingRange,omitempty"`
	SelectionRange     *SelectionRangeClientCapabilities           `json:"selectionRange,omitempty"`
	PublishDiagnostics *PublishDiagnosticsClientCapabilities       `json:"publishDiagnostics,omitempty"`
	CallHierarchy      *CallHierarchyClientCapabilities            `json:"callHierarchy,omitempty"`
	SemanticTokens     *SemanticTokensClientCapabilities           `json:"semanticTokens,omitempty"`
	LinkedEditingRange *LinkedEditingRangeClientCapabilities       `json:"linkedEditingRange,omitempty"`
	Moniker            *MonikerClientCapabilities                  `json:"moniker,omitempty"`
	TypeHierarchy      *TypeHierarchyClientCapabilities            `json:"typeHierarchy,omitempty"`
	InlineValue        *InlineValueClientCapabilities              `json:"inlineValue,omitempty"`
	InlayHint          *InlayHintClientCapabilities                `json:"inlayHint,omitempty"`
	Diagnostic         *DiagnosticClientCapabilities               `json:"diagnostic,omitempty"`
	InlineCompletion   *InlineCompletionClientCapabilities         `json:"inlineCompletion,omitempty"`
}

type TextDocumentContentChangeEvent = json.RawMessage

type TextDocumentContentChangePartial struct {
	Range       Range   `json:"range"`
	RangeLength *uint32 `json:"rangeLength,omitempty"`
	Text        string  `json:"text"`
}

type TextDocumentContentChangeWholeDocument struct {
	Text string `json:"text"`
}

type TextDocumentContentClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type TextDocumentContentOptions struct {
	Schemes []string `json:"schemes"`
}

type TextDocumentContentRegistrationOptions struct {
	Schemes []string `json:"schemes"`
	Id      *string  `json:"id,omitempty"`
}

type TextDocumentFilterClientCapabilities struct {
	RelativePatternSupport *bool `json:"relativePatternSupport,omitempty"`
}

type TextDocumentIdentifier struct {
	Uri string `json:"uri"`
}

type TextDocumentItem struct {
	Uri        string       `json:"uri"`
	LanguageId LanguageKind `json:"languageId"`
	Version    int32        `json:"version"`
	Text       string       `json:"text"`
}

type TextDocumentPositionParams struct {
	TextDocument TextDocumentIdentifier `json:"textDocument"`
	Position     Position               `json:"position"`
}

type TextDocumentRegistrationOptions struct {
	DocumentSelector json.RawMessage `json:"documentSelector"`
}

type TextDocumentSyncClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	WillSave            *bool `json:"willSave,omitempty"`
	WillSaveWaitUntil   *bool `json:"willSaveWaitUntil,omitempty"`
	DidSave             *bool `json:"didSave,omitempty"`
}

type TextDocumentSyncKind uint32

const (
	TextDocumentSyncKindNone        TextDocumentSyncKind = 0
	TextDocumentSyncKindFull        TextDocumentSyncKind = 1
	TextDocumentSyncKindIncremental TextDocumentSyncKind = 2
)

type TextDocumentSyncOptions struct {
	OpenClose         *bool                 `json:"openClose,omitempty"`
	Change            *TextDocumentSyncKind `json:"change,omitempty"`
	WillSave          *bool                 `json:"willSave,omitempty"`
	WillSaveWaitUntil *bool                 `json:"willSaveWaitUntil,omitempty"`
	Save              json.RawMessage       `json:"save,omitempty"`
}

type TokenFormat string

const (
	TokenFormatRelative TokenFormat = "relative"
)

type TraceValue string

const (
	TraceValueOff      TraceValue = "off"
	TraceValueMessages TraceValue = "messages"
	TraceValueVerbose  TraceValue = "verbose"
)

type TypeDefinitionClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
	LinkSupport         *bool `json:"linkSupport,omitempty"`
}

type TypeDefinitionOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type TypeDefinitionRegistrationOptions struct {
	DocumentSelector json.RawMessage `json:"documentSelector"`
	WorkDoneProgress *bool           `json:"workDoneProgress,omitempty"`
	Id               *string         `json:"id,omitempty"`
}

type TypeHierarchyClientCapabilities struct {
	DynamicRegistration *bool `json:"dynamicRegistration,omitempty"`
}

type TypeHierarchyOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type TypeHierarchyRegistrationOptions struct {
	DocumentSelector json.RawMessage `json:"documentSelector"`
	WorkDoneProgress *bool           `json:"workDoneProgress,omitempty"`
	Id               *string         `json:"id,omitempty"`
}

type UnchangedDocumentDiagnosticReport struct {
	Kind     string `json:"kind"`
	ResultId string `json:"resultId"`
}

type VersionedTextDocumentIdentifier struct {
	Uri     string `json:"uri"`
	Version int32  `json:"version"`
}

type WindowClientCapabilities struct {
	WorkDoneProgress *bool                                 `json:"workDoneProgress,omitempty"`
	ShowMessage      *ShowMessageRequestClientCapabilities `json:"showMessage,omitempty"`
	ShowDocument     *ShowDocumentClientCapabilities       `json:"showDocument,omitempty"`
}

type WorkDoneProgressBegin struct {
	Kind        string  `json:"kind"`
	Title       string  `json:"title"`
	Cancellable *bool   `json:"cancellable,omitempty"`
	Message     *string `json:"message,omitempty"`
	Percentage  *uint32 `json:"percentage,omitempty"`
}

type WorkDoneProgressCreateParams struct {
	Token json.RawMessage `json:"token"`
}

type WorkDoneProgressEnd struct {
	Kind    string  `json:"kind"`
	Message *string `json:"message,omitempty"`
}

type WorkDoneProgressOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
}

type WorkDoneProgressParams struct {
	WorkDoneToken json.RawMessage `json:"workDoneToken,omitempty"`
}

type WorkDoneProgressReport struct {
	Kind        string  `json:"kind"`
	Cancellable *bool   `json:"cancellable,omitempty"`
	Message     *string `json:"message,omitempty"`
	Percentage  *uint32 `json:"percentage,omitempty"`
}

type WorkspaceClientCapabilities struct {
	ApplyEdit              *bool                                      `json:"applyEdit,omitempty"`
	WorkspaceEdit          *WorkspaceEditClientCapabilities           `json:"workspaceEdit,omitempty"`
	DidChangeConfiguration *DidChangeConfigurationClientCapabilities  `json:"didChangeConfiguration,omitempty"`
	DidChangeWatchedFiles  *DidChangeWatchedFilesClientCapabilities   `json:"didChangeWatchedFiles,omitempty"`
	Symbol                 *WorkspaceSymbolClientCapabilities         `json:"symbol,omitempty"`
	ExecuteCommand         *ExecuteCommandClientCapabilities          `json:"executeCommand,omitempty"`
	WorkspaceFolders       *bool                                      `json:"workspaceFolders,omitempty"`
	Configuration          *bool                                      `json:"configuration,omitempty"`
	SemanticTokens         *SemanticTokensWorkspaceClientCapabilities `json:"semanticTokens,omitempty"`
	CodeLens               *CodeLensWorkspaceClientCapabilities       `json:"codeLens,omitempty"`
	FileOperations         *FileOperationClientCapabilities           `json:"fileOperations,omitempty"`
	InlineValue            *InlineValueWorkspaceClientCapabilities    `json:"inlineValue,omitempty"`
	InlayHint              *InlayHintWorkspaceClientCapabilities      `json:"inlayHint,omitempty"`
	Diagnostics            *DiagnosticWorkspaceClientCapabilities     `json:"diagnostics,omitempty"`
	FoldingRange           *FoldingRangeWorkspaceClientCapabilities   `json:"foldingRange,omitempty"`
	TextDocumentContent    *TextDocumentContentClientCapabilities     `json:"textDocumentContent,omitempty"`
}

type WorkspaceEditClientCapabilities struct {
	DocumentChanges         *bool                            `json:"documentChanges,omitempty"`
	ResourceOperations      []ResourceOperationKind          `json:"resourceOperations,omitempty"`
	FailureHandling         *FailureHandlingKind             `json:"failureHandling,omitempty"`
	NormalizesLineEndings   *bool                            `json:"normalizesLineEndings,omitempty"`
	ChangeAnnotationSupport *ChangeAnnotationsSupportOptions `json:"changeAnnotationSupport,omitempty"`
	MetadataSupport         *bool                            `json:"metadataSupport,omitempty"`
	SnippetEditSupport      *bool                            `json:"snippetEditSupport,omitempty"`
}

type WorkspaceFolder struct {
	Uri  string `json:"uri"`
	Name string `json:"name"`
}

type WorkspaceFoldersInitializeParams struct {
	WorkspaceFolders []WorkspaceFolder `json:"workspaceFolders,omitempty"`
}

type WorkspaceFoldersServerCapabilities struct {
	Supported           *bool           `json:"supported,omitempty"`
	ChangeNotifications json.RawMessage `json:"changeNotifications,omitempty"`
}

type WorkspaceOptions struct {
	WorkspaceFolders    *WorkspaceFoldersServerCapabilities `json:"workspaceFolders,omitempty"`
	FileOperations      *FileOperationOptions               `json:"fileOperations,omitempty"`
	TextDocumentContent json.RawMessage                     `json:"textDocumentContent,omitempty"`
}

type WorkspaceSymbolClientCapabilities struct {
	DynamicRegistration *bool                       `json:"dynamicRegistration,omitempty"`
	SymbolKind          *ClientSymbolKindOptions    `json:"symbolKind,omitempty"`
	TagSupport          *ClientSymbolTagOptions     `json:"tagSupport,omitempty"`
	ResolveSupport      *ClientSymbolResolveOptions `json:"resolveSupport,omitempty"`
}

type WorkspaceSymbolOptions struct {
	WorkDoneProgress *bool `json:"workDoneProgress,omitempty"`
	ResolveProvider  *bool `json:"resolveProvider,omitempty"`
}
