// Command dowse-gen generates Go types from the LSP metaModel.json.
//
//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

// MetaModel is the top-level structure of the LSP metaModel.json.
type MetaModel struct {
	Structures   []Structure   `json:"structures"`
	Enumerations []Enumeration `json:"enumerations"`
	TypeAliases  []TypeAlias   `json:"typeAliases"`
}

type Structure struct {
	Name       string     `json:"name"`
	Properties []Property `json:"properties"`
	Extends    []TypeRef  `json:"extends"`
	Mixins     []TypeRef  `json:"mixins"`
}

type Property struct {
	Name     string  `json:"name"`
	Type     TypeRef `json:"type"`
	Optional bool    `json:"optional"`
}

type TypeRef struct {
	Kind       string          `json:"kind"`
	Name       string          `json:"name"`
	RawValue   json.RawMessage `json:"value"`
	Items      []TypeRef       `json:"items"`
	Element    *TypeRef        `json:"element"`
	Key        *TypeRef        `json:"key"`
	Properties []Property      `json:"properties"`
}

// ValueTypeRef parses the "value" field as a TypeRef (used by map types).
func (t TypeRef) ValueTypeRef() *TypeRef {
	if len(t.RawValue) == 0 {
		return nil
	}
	trimmed := bytes.TrimSpace(t.RawValue)
	if len(trimmed) == 0 || trimmed[0] != '{' {
		return nil
	}
	var ref TypeRef
	if err := json.Unmarshal(t.RawValue, &ref); err != nil {
		return nil
	}
	return &ref
}

type Enumeration struct {
	Name   string      `json:"name"`
	Type   TypeRef     `json:"type"`
	Values []EnumValue `json:"values"`
}

type EnumValue struct {
	Name  string `json:"name"`
	Value any    `json:"value"`
}

type TypeAlias struct {
	Name   string      `json:"name"`
	Type   TypeRef     `json:"type"`
	Values []EnumValue `json:"values"`
}

// V1 allow list of root type names.
var allowList = []string{
	"InitializeParams",
	"InitializeResult",
	"ServerCapabilities",
	"ClientCapabilities",
	"TextDocumentItem",
	"VersionedTextDocumentIdentifier",
	"TextDocumentIdentifier",
	"DidOpenTextDocumentParams",
	"DidChangeTextDocumentParams",
	"DidCloseTextDocumentParams",
	"PublishDiagnosticsParams",
	"DocumentDiagnosticParams",
	"FullDocumentDiagnosticReport",
	"RelatedFullDocumentDiagnosticReport",
	"Diagnostic",
	"DiagnosticSeverity",
	"DiagnosticTag",
	"Range",
	"Position",
	"TextDocumentSyncOptions",
	"DiagnosticOptions",
	"WorkDoneProgressCreateParams",
	"ProgressParams",
	"WorkDoneProgressBegin",
	"WorkDoneProgressReport",
	"WorkDoneProgressEnd",
	"DefinitionParams",
	"TextDocumentPositionParams",
}

type generator struct {
	model     MetaModel
	structMap map[string]*Structure
	enumMap   map[string]*Enumeration
	aliasMap  map[string]*TypeAlias
	needed    map[string]bool // types we need to emit
	buf       bytes.Buffer
	emitted   map[string]bool
}

func main() {
	if len(os.Args) < 2 {
		log.Fatal("usage: go run main.go <metaModel.json>")
	}

	data, err := os.ReadFile(os.Args[1])
	if err != nil {
		log.Fatal(err)
	}

	var model MetaModel
	if err := json.Unmarshal(data, &model); err != nil {
		log.Fatal(err)
	}

	g := &generator{
		model:     model,
		needed:    make(map[string]bool),
		emitted:   make(map[string]bool),
		structMap: make(map[string]*Structure),
		enumMap:   make(map[string]*Enumeration),
		aliasMap:  make(map[string]*TypeAlias),
	}

	for i := range model.Structures {
		g.structMap[model.Structures[i].Name] = &model.Structures[i]
	}
	for i := range model.Enumerations {
		g.enumMap[model.Enumerations[i].Name] = &model.Enumerations[i]
	}
	for i := range model.TypeAliases {
		g.aliasMap[model.TypeAliases[i].Name] = &model.TypeAliases[i]
	}

	// Seed with allow list and resolve transitive dependencies.
	for _, name := range allowList {
		g.resolve(name)
	}

	// Generate output.
	g.printf("// Code generated by dowse-gen; DO NOT EDIT.\n\n")
	g.printf("package protocol\n\n")
	g.printf("import \"encoding/json\"\n\n")
	g.printf("// Ensure json import is used.\nvar _ = json.RawMessage{}\n\n")

	// Emit all needed types in sorted order for deterministic output.
	names := make([]string, 0, len(g.needed))
	for name := range g.needed {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		g.emit(name)
	}

	src, err := format.Source(g.buf.Bytes())
	if err != nil {
		// Write unformatted source for debugging.
		os.WriteFile("types_generated_debug.go", g.buf.Bytes(), 0644)
		log.Fatalf("gofmt failed: %v", err)
	}

	outDir := filepath.Dir(os.Args[1])
	outPath := filepath.Join(outDir, "..", "protocol", "types_generated.go")
	if err := os.WriteFile(outPath, src, 0644); err != nil {
		log.Fatal(err)
	}

	fmt.Fprintf(os.Stderr, "Generated %s (%d bytes, %d types)\n", outPath, len(src), len(g.needed))
}

// resolve marks a type name as needed and recursively resolves its dependencies.
func (g *generator) resolve(name string) {
	if name == "" || g.needed[name] {
		return
	}
	// Skip well-known base/special types that we handle inline.
	if isSpecialAlias(name) {
		return
	}
	g.needed[name] = true

	if structure, ok := g.structMap[name]; ok {
		g.resolveStructDeps(structure)
		return
	}
	if enum, ok := g.enumMap[name]; ok {
		g.resolveTypeDeps(enum.Type)
		return
	}
	if alias, ok := g.aliasMap[name]; ok {
		g.resolveTypeDeps(alias.Type)
		// If it has enum values, no extra deps.
		return
	}
}

func (g *generator) resolveStructDeps(structure *Structure) {
	for _, ext := range structure.Extends {
		g.resolveTypeDeps(ext)
	}
	for _, mix := range structure.Mixins {
		g.resolveTypeDeps(mix)
	}
	for _, prop := range structure.Properties {
		g.resolveTypeDeps(prop.Type)
	}
}

func (g *generator) resolveTypeDeps(typeRef TypeRef) {
	switch typeRef.Kind {
	case "reference":
		g.resolve(typeRef.Name)
	case "array":
		if typeRef.Element != nil {
			g.resolveTypeDeps(*typeRef.Element)
		}
	case "or":
		for _, item := range typeRef.Items {
			g.resolveTypeDeps(item)
		}
	case "map":
		if typeRef.Key != nil {
			g.resolveTypeDeps(*typeRef.Key)
		}
		if value := typeRef.ValueTypeRef(); value != nil {
			g.resolveTypeDeps(*value)
		}
	case "literal":
		for _, prop := range typeRef.Properties {
			g.resolveTypeDeps(prop.Type)
		}
	case "base", "stringLiteral", "tuple":
		// no deps
	}
}

// emit generates Go code for the named type.
func (g *generator) emit(name string) {
	goName := exportName(name)
	if g.emitted[goName] {
		return
	}
	g.emitted[goName] = true

	if structure, ok := g.structMap[name]; ok {
		g.emitStruct(structure)
		return
	}
	if enum, ok := g.enumMap[name]; ok {
		g.emitEnum(enum)
		return
	}
	if alias, ok := g.aliasMap[name]; ok {
		g.emitAlias(alias)
		return
	}
}

func (g *generator) emitStruct(structure *Structure) {
	goName := exportName(structure.Name)
	g.printf("type %s struct {\n", goName)

	// Collect all properties: from extends, mixins, and own.
	allProps := g.collectAllProperties(structure)

	seen := make(map[string]bool)
	for _, prop := range allProps {
		if seen[prop.Name] {
			continue
		}
		seen[prop.Name] = true

		fieldName := exportName(prop.Name)
		goType := g.goType(prop.Type, prop.Optional)

		jsonTag := prop.Name
		if prop.Optional {
			jsonTag += ",omitempty"
		}
		g.printf("\t%s %s `json:\"%s\"`\n", fieldName, goType, jsonTag)
	}

	g.printf("}\n\n")
}

// collectAllProperties gathers properties from extends, mixins, and own.
func (g *generator) collectAllProperties(structure *Structure) []Property {
	var all []Property

	for _, ext := range structure.Extends {
		if ext.Kind == "reference" {
			if parent, ok := g.structMap[ext.Name]; ok {
				all = append(all, g.collectAllProperties(parent)...)
			}
		}
	}
	for _, mix := range structure.Mixins {
		if mix.Kind == "reference" {
			if parent, ok := g.structMap[mix.Name]; ok {
				all = append(all, g.collectAllProperties(parent)...)
			}
		}
	}
	all = append(all, structure.Properties...)
	return all
}

func (g *generator) emitEnum(enum *Enumeration) {
	goName := exportName(enum.Name)
	baseType := g.baseGoType(enum.Type)

	g.printf("type %s %s\n\n", goName, baseType)
	g.printf("const (\n")
	for _, value := range enum.Values {
		constName := goName + exportName(value.Name)
		switch baseType {
		case "string":
			g.printf("\t%s %s = %q\n", constName, goName, value.Value)
		default:
			// integer enum
			g.printf("\t%s %s = %v\n", constName, goName, formatIntValue(value.Value))
		}
	}
	g.printf(")\n\n")
}

func (g *generator) emitAlias(alias *TypeAlias) {
	goName := exportName(alias.Name)

	// If it has enum values, treat like an enum.
	if len(alias.Values) > 0 {
		baseType := g.baseGoType(alias.Type)
		g.printf("type %s %s\n\n", goName, baseType)
		g.printf("const (\n")
		for _, value := range alias.Values {
			constName := goName + exportName(value.Name)
			switch baseType {
			case "string":
				g.printf("\t%s %s = %q\n", constName, goName, value.Value)
			default:
				g.printf("\t%s %s = %v\n", constName, goName, formatIntValue(value.Value))
			}
		}
		g.printf(")\n\n")
		return
	}

	// Otherwise emit a type alias.
	goType := g.goTypeForAlias(alias.Type)
	g.printf("type %s = %s\n\n", goName, goType)
}

// goType returns the Go type string for a metamodel type reference.
// If optional is true and the type is a value type, it wraps in a pointer.
func (g *generator) goType(typeRef TypeRef, optional bool) string {
	typ := g.goTypeInner(typeRef)
	if optional && needsPointer(typ) {
		return "*" + typ
	}
	return typ
}

func (g *generator) goTypeInner(typeRef TypeRef) string {
	switch typeRef.Kind {
	case "base":
		return baseToGo(typeRef.Name)
	case "reference":
		if isSpecialAlias(typeRef.Name) {
			return specialAliasType(typeRef.Name)
		}
		return exportName(typeRef.Name)
	case "array":
		if typeRef.Element != nil {
			return "[]" + g.goTypeInner(*typeRef.Element)
		}
		return "[]any"
	case "or":
		return g.orType(typeRef)
	case "map":
		keyType := "string"
		if typeRef.Key != nil {
			keyType = g.goTypeInner(*typeRef.Key)
		}
		valType := "any"
		if value := typeRef.ValueTypeRef(); value != nil {
			valType = g.goTypeInner(*value)
		}
		return fmt.Sprintf("map[%s]%s", keyType, valType)
	case "literal":
		return g.literalType(typeRef)
	case "stringLiteral":
		return "string"
	case "tuple":
		return "[]any"
	default:
		return "any"
	}
}

func (g *generator) goTypeForAlias(typeRef TypeRef) string {
	switch typeRef.Kind {
	case "base":
		return baseToGo(typeRef.Name)
	case "reference":
		if isSpecialAlias(typeRef.Name) {
			return specialAliasType(typeRef.Name)
		}
		return exportName(typeRef.Name)
	case "or":
		return g.orType(typeRef)
	case "array":
		if typeRef.Element != nil {
			return "[]" + g.goTypeInner(*typeRef.Element)
		}
		return "[]any"
	case "map":
		keyType := "string"
		if typeRef.Key != nil {
			keyType = g.goTypeInner(*typeRef.Key)
		}
		valType := "any"
		if value := typeRef.ValueTypeRef(); value != nil {
			valType = g.goTypeInner(*value)
		}
		return fmt.Sprintf("map[%s]%s", keyType, valType)
	default:
		return "any"
	}
}

// orType handles union types. Strategy:
// - If one branch is "null", use the non-null type (pointer handled by optional).
// - If two branches and one is a concrete type, use json.RawMessage.
// - Otherwise, json.RawMessage.
func (g *generator) orType(typeRef TypeRef) string {
	nonNull := filterNull(typeRef.Items)

	if len(nonNull) == 1 {
		return g.goTypeInner(nonNull[0])
	}

	// If all non-null items are references/base that could be a single concept, use RawMessage.
	return "json.RawMessage"
}

func (g *generator) literalType(typeRef TypeRef) string {
	if len(typeRef.Properties) == 0 {
		return "map[string]any"
	}

	// Generate an inline struct.
	var buf strings.Builder
	buf.WriteString("struct {\n")
	for _, prop := range typeRef.Properties {
		fieldName := exportName(prop.Name)
		goType := g.goType(prop.Type, prop.Optional)
		jsonTag := prop.Name
		if prop.Optional {
			jsonTag += ",omitempty"
		}
		fmt.Fprintf(&buf, "\t\t%s %s `json:\"%s\"`\n", fieldName, goType, jsonTag)
	}
	buf.WriteString("\t}")
	return buf.String()
}

func filterNull(items []TypeRef) []TypeRef {
	var result []TypeRef
	for _, item := range items {
		if item.Kind == "base" && item.Name == "null" {
			continue
		}
		result = append(result, item)
	}
	return result
}

func baseToGo(name string) string {
	switch name {
	case "string", "DocumentUri", "URI":
		return "string"
	case "integer":
		return "int32"
	case "uinteger":
		return "uint32"
	case "decimal":
		return "float64"
	case "boolean":
		return "bool"
	case "null":
		return "any"
	default:
		return "any"
	}
}

// baseGoType returns the Go base type for an enumeration's underlying type.
func (g *generator) baseGoType(typeRef TypeRef) string {
	switch typeRef.Kind {
	case "base":
		return baseToGo(typeRef.Name)
	default:
		return "any"
	}
}

// needsPointer returns true for value types that need a pointer when optional.
func needsPointer(goType string) bool {
	switch goType {
	case "bool", "int32", "uint32", "float64", "string":
		return true
	}
	// Enum types (single-word, exported) also need pointers.
	if len(goType) > 0 && unicode.IsUpper(rune(goType[0])) && !strings.HasPrefix(goType, "[]") && !strings.HasPrefix(goType, "map[") && !strings.HasPrefix(goType, "json.") && !strings.HasPrefix(goType, "struct") && !strings.HasPrefix(goType, "*") {
		return true
	}
	return false
}

// isSpecialAlias returns true for type names that should be mapped to
// Go types directly rather than being generated.
func isSpecialAlias(name string) bool {
	switch name {
	case "LSPAny", "LSPObject", "LSPArray", "DocumentUri", "URI",
		"ProgressToken", "DocumentSelector":
		return true
	}
	return false
}

func specialAliasType(name string) string {
	switch name {
	case "LSPAny":
		return "json.RawMessage"
	case "LSPObject":
		return "map[string]any"
	case "LSPArray":
		return "[]any"
	case "DocumentUri", "URI":
		return "string"
	case "ProgressToken":
		return "json.RawMessage"
	case "DocumentSelector":
		return "json.RawMessage"
	default:
		return "any"
	}
}

func exportName(name string) string {
	if name == "" {
		return ""
	}
	// Handle underscore-prefixed names like _InitializeParams.
	clean := strings.TrimPrefix(name, "_")
	if clean == "" {
		return ""
	}
	// Capitalize first letter.
	runes := []rune(clean)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func formatIntValue(value any) string {
	switch val := value.(type) {
	case float64:
		return fmt.Sprintf("%d", int(val))
	case int:
		return fmt.Sprintf("%d", val)
	default:
		return fmt.Sprintf("%v", val)
	}
}

func (g *generator) printf(format string, args ...any) {
	fmt.Fprintf(&g.buf, format, args...)
}
